### PR TITLE
Add top_level_domain domain field as proposed by ECS

### PR DESCRIPTION
**Pull request by vogtp**
Add top_level_domain domain field as proposed by ECS

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by vogtp** [comment]
Signing the contributor agreement is more complicated than my change.
In case it did not work: I do not claim any rights on my change and declare that it is free to use.

**Comment by vogtp** [comment]
OK, not really useful right now...

I wanted to do something like this:
        tld {
            source => "[source][name]"
            target => "[source]"
        }

It would need something like:
      h = Hash.new
      if event.get(@target).is_a?(Hash)
          h = event.get(@target)
      end  

But I am not too sure if this would work, but I am happy to implement it if this is a good idea.

**Comment by kares** [comment]
Thanks for your efforts, this seems to make sense in context of ECS.
Given a `target` such as `"server"` would set [`server.top_level_domain`](https://github.com/elastic/ecs/blob/1.7/generated/ecs/ecs_flat.yml#L6210).

For this PR to be merged we would need a test, version bump and changelog entry.

**Review by kares — APPROVED** [review]
LGTM, CI failures does not seem to be related to the changes

**Pull request merged**
